# Generated by Django 4.0.5 on 2023-09-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
