# Generated by Django 4.0.5 on 2023-09-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatconversation_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatconversation',
            old_name='response',
            new_name='bot_response',
        ),
        migrations.RemoveField(
            model_name='chatconversation',
            name='messages',
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='user_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
